### ISSUE TITLE
ATata Screenshots Configuration

### ISSUE THREAD

**Issue by swapniljagtap** [atata-framework/atata#139]
Hi,

This is Swapnil Jagtap from India. I want to configure my ATata project to take screenshot of every testcase. I am able to do that for TakeScreenshotOnNUnitError() method, but not able to do for every testcase. Idid following configuration in Fixture page.
AddScreenshotFileSaving().
            WithFolderPath(() => $@"Logs\{AtataContext.BuildStart:yyyy-MM-dd HH_mm_ss}\{AtataContext.Current.TestName}").
            WithFileName(screenshotInfo => $"{screenshotInfo.Number:D2} - {screenshotInfo.PageObjectFullName}{screenshotInfo.Title?.Prepend(" - ")}").
Build();

Can you please send one sample project with screenshot configuration. This would be very helpful for my project.

Thanks in advance.

**Comment by YevgeniyShunevych** [comment]
Hi Swapnil, 

To take screenshot you can use `AtataContext.Current.Log.Screenshot("Optional title")` method.

If you want to take screenshot at the end of each test, just modify `TearDown` method:

```cs
[TearDown]
public void TearDown()
{
    AtataContext.Current.Log.Screenshot();
    AtataContext.Current.CleanUp();
}
```

In this case you will need to remove using of `TakeScreenshotOnNUnitError` method, because it will duplicate screenshot.
