### ISSUE TITLE
UseRemoteDriver WithAlias throws an error

### ISSUE THREAD

**Issue by nofear217** [atata-framework/atata#282]
I'm using the following in a SetupFixture in the OneTimeSetup Method:

`AtataContext.Configure()
                .UseRemoteDriver()
                    .WithAlias("chrome_remote")
                    .WithRemoteAddress(<someUrl>)
                    .WithOptions(chromeOptions)`

and then this in the UITestFixture base test class:

`[TestFixture("chrome_remote")]`

When I initiate a test, I get the following error:

`System.ArgumentException : No driver with "chrome_remote" alias defined.
Parameter name: alias
   at Atata.AtataContextBuilder.UseDriver(String alias)
   at AtataFrameworkTest.UITestFixture.SetUp() in C:\Users\jeremy.sydnor\source\repos\empireautomationframework\EmpireAutomationFramework\AtataFrameworkTest\UITestFixture.cs:line 24
`

Not sure what I'm doing wrong, any help is appreciated.  For what it's worth, I'm hoping to have multiple UseRemoteDriver configs setup there with multiple aliases.

**Comment by YevgeniyShunevych** [comment]
If you are using `OneTimeSetup` in `SetupFixture` then instead of `AtataContext.Configure()` use `AtataContext.GlobalConfiguration` property like [here for example](https://github.com/atata-framework/atata-samples/blob/master/MultipleBrowsersViaFixtureArguments/AtataSamples.MultipleBrowsersViaFixtureArguments/SetUpFixture.cs) from [atata-samples/MultipleBrowsersViaFixtureArguments](https://github.com/atata-framework/atata-samples/tree/master/MultipleBrowsersViaFixtureArguments) sample.

**Comment by nofear217** [comment]
Aha! Knew it must have been something simple.  That did it, thank you.

**Comment by YevgeniyShunevych** [comment]
Sure, welcome.
