### ISSUE TITLE
Logged sections don't use time zone configuration

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#501]
Atata 1.11.0 adds timezone configuration for logging. This works well with `Log.Trace()` but messages logged via `Log.ExecuteSection()` still emit in the local timezone.

E.g. "Clean up AtataContext" is logged with the local time zone but "Set up AtataContext" is correctly logged with the configured time zone. As the configuration I only tried `AtataContext.Configure().UseUtcTimeZone()`.

**Comment by YevgeniyShunevych** [comment]
I assume that it happened because `AtataContext.Current` was `null` at that moment. You can check [LogEventInfo](https://github.com/atata-framework/atata/blob/524d01134404a970db16045ea66706e9c820c3f4/src/Atata/Logging/LogEventInfo.cs#L19). #504 fix should probably solve this problem for you.

Thanks a lot for testing latest Atata version features and fast feedback. I will make another Atata fix release.

**Comment by Piedone** [comment]
I haven't used `AtataNavigator` yet so it's not related to it. However, it does seem that it's because of `AtataContext.Current`. I've added some `AtataContext.Current = myContext` assignments and it helped.

So I guess this is not an issue with the release specifically but rather with the reliance on `AtataContext.Current`. This is something we've touched on under https://github.com/atata-framework/atata/issues/364 too: I think it would be better to pass (at least optionally) an `AtataContext` around so if you want to you don't have to rely on the static property.

There's nothing to fix here then I assume?

**Comment by YevgeniyShunevych** [comment]
Thanks, I reviewed that and made another #505 fix.

I have just released Atata v1.11.1 with fixes. Please update to it and verify your issues, when you'll have a time.

**Comment by Piedone** [comment]
Thanks, this fixed those issues.

**Comment by YevgeniyShunevych** [comment]
This is great.
