### ISSUE TITLE
Atata in a production environment

### ISSUE THREAD

**Issue by gustavomoises** [atata-framework/atata#546]
Atata Team,

Is it possible to apply Atata to implement workflows in a production environment? 

For instance, when the user clicks a button, the following steps should be completed automatically: click a specific link and in the new page click another button. The users is already logged in.

Thanks,

Gustavo

**Comment by YevgeniyShunevych** [comment]
I just want to clarify. You want to have a single test case partially manual and partially automated with Atata? Do initial actions, like login, manually and then execute automatic test that will continue and complete the test case?

**Comment by gustavomoises** [comment]
@YevgeniyShunevych  It is exactly as you described. The user is logged in and Atata should take the control and complete a sequence of events.

**Comment by YevgeniyShunevych** [comment]
OK. I'm not telling, that we cannot do that with Atata. We actually can try to implement something. But, I would like to try to convince you first to make it in completely automatic way. Otherwise you will not be able to run such tests, which requires manual actions, in CI/CD pipelines. Which is really cool to have everything be runnable on CI. I understand that you want to keep login/password in secret for production environment. But you can use CI secret variables (I assume that any CI system has such feature) to store sensitive information there and pass this data to tests application via environment variable, for example. Then in a tests library on a global setup you can read this data and additionally tell Atata to mask this data in log.

```cs
string somePassword = Environment.GetEnvironmentVariable("SomePassword");

AtataContext.GlobalConfiguration
    .AddSecretStringToMaskInLog(somePassword);
```

Let me know if I haven't convinced you.

**Comment by gustavomoises** [comment]
Thanks @YevgeniyShunevych. I will think about it.
